version: '3.8'

services:
  nginx:
    build: 
      context: ./requirements/nginx
      network: host 
    restart: unless-stopped
    ports: 
      - 443:443
    networks:
      - my_awesome_network
    # volumes:
    #   - wp_data:/var/www/html
    volumes_from:
      - wordpress:rw
    
  wordpress:
    build: 
      context: ./requirements/wordpress
      network: host
    restart: unless-stopped
    networks:
      - my_awesome_network
    volumes:
      - wp_data:/var/www/html:z
    env_file:
      - .env
    environment:
      - DB_HOST=mariadb

  mariadb:
    build: 
      context: ./requirements/mariadb
      network: host
    restart: unless-stopped
    networks:
      - my_awesome_network
    volumes:
      - db_data:/var/lib/mysql
    env_file:
      - .env
  redis:
    build:
      context: ./requirements/mariadb
      network: host
    restart: unless-stopped
    networks:
      - my_awesome_network

  ftp:
    build: ./requirements/bonus/ftp/.
    depends_on:
      - wordpress
    volumes:
      - wp_data:/home/sami/ftp/files
    env_file:
      - .env
    ports:
      - "21:21"
      - "20:20"
      - "40000-40005:40000-40005"
    networks:
      - my_awesome_network
    # restart: always


volumes:
  db_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: $HOME/data/db_data
  wp_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: $HOME/data/wp_data

networks:
  my_awesome_network:
