version: '3.8'

services:
  nginx:
    build: 
      context: ./requirements/nginx
      network: host 
    networks:
      - my_awesome_network
    volumes:
      - wp_data:/var/www/html
    
  wordpress:
    build: 
      context: ./requirements/wordpress
      network: host
    ports: 
      - 9000
    networks:
      - my_awesome_network
    volumes:
      - wp_data:/var/www/html
      

  # mariadb:
  #   build: ./requirements/mariadb


volumes:
  db_data:
  wp_data:

networks:
  my_awesome_network:
