version: '3.8'

services:
  nginx:
    build: 
      context: ./requirements/nginx
      network: host 
    ports: 
      - 443:443
    networks:
      - my_awesome_network
    volumes_from:
      - wordpress:rw
    
  wordpress:
    build: 
      context: ./requirements/wordpress
      network: host
    ports: 
      - 9000
    networks:
      - my_awesome_network
    volumes:
      - wp_data:/var/www/html
      

  # mariadb:
  #   build: ./requirements/mariadb


volumes:
  db_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: $HOME/data/db_data
  wp_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: $HOME/data/wp_data

networks:
  my_awesome_network:
