version: '3.8'

services:
  nginx:
    build: 
      context: ./requirements/nginx
      network: host 
    restart: unless-stopped
    ports: 
      - 443:443
    networks:
      - my_awesome_network
    # volumes:
    #   - wp_data:/var/www/html
    volumes_from:
      - wordpress:rw
    
  wordpress:
    build: 
      context: ./requirements/wordpress
      network: host
      args:
        - WORDPRESS_DB_USER=${WORDPRESS_DB_USER}
    restart: unless-stopped
    ports: 
      - 9000
    networks:
      - my_awesome_network
    volumes:
      - wp_data:/var/www/html:z
    env_file:
      - .env
    environment:
      - DB_HOST=mariadb

  mariadb:
    build: 
      context: ./requirements/mariadb
      network: host
    # restart: unless-stopped
    ports: 
      - 3306
    networks:
      - my_awesome_network
    volumes:
      - db_data:/var/lib/mysql
    env_file:
      - .env


volumes:
  db_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: $HOME/data/db_data
  wp_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: $HOME/data/wp_data

networks:
  my_awesome_network:
